exports.banks = [
    { id: 'ICBC',
        bankName: 'Industrial and Commercial Bank of China',
        asset: '$4,027 bln',
        country: 'China' },
    { id: 'CCBC',
        bankName: 'China Construction Bank Corporation',
        asset: '$3,377 bln',
        country: 'China' },
    { id: 'ABC',
        bankName: 'Agricultural Bank of China',
        asset: '$3,287 bln',
        country: 'China' },
    { id: 'BCL', bankName: 'Bank of China ltd', asset: '$3,092 bln', country: 'China' },
    { id: 'MUFJ',
        bankName: 'Mitsubishi UFJ Financial Group',
        asset: '$3,069 bln',
        country: 'Japan' },
    { id: 'JPMorgan', bankName: 'JPMorgan Chase', asset: '$2,727 bln', country: 'USA' },
    { id: 'HSBC', bankName: 'HSBC Holdings plc', asset: '$2,558 bln', country: 'England' },
    { id: 'BoA', bankName: 'Bank of America', asset: '$2,354 bln', country: 'USA' },
    { id: 'BNP', bankName: 'BNP Pariba', asset: '$2,336 bln', country: 'France' },
    { id: 'CA', bankName: 'Crédit Agricole', asset: '$2,123 bln', country: 'France' }
]
