exports.banks = [
    { id: 'ICBC',
        currency: 'USD',
        bankName: 'Industrial and Commercial Bank of China',
        asset: '$4,000 bln',
        value: 4000000000,
        country: 'China' },
    { id: 'CCBC',
        currency: 'USD',
        bankName: 'China Construction Bank Corporation',
        asset: '$3,000 bln',
        value: 3000000000,
        country: 'China' },
    { id: 'ABC',
        currency: 'USD',
        bankName: 'Agricultural Bank of China',
        asset: '$3,000 bln',
        value: 3000000000,
        country: 'China' },
    { id: 'BCL',
        currency: 'USD',
        bankName: 'Bank of China ltd',
        asset: '$3,092 bln',
        country: 'China' },
    { id: 'MUFJ',
        currency: 'USD',
        bankName: 'Mitsubishi UFJ Financial Group',
        asset: '$3,000 bln',
        value: 3000000000,
        country: 'Japan' },
    { id: 'JPMorgan',
        currency: 'USD',
        bankName: 'JPMorgan Chase',
        asset: '$2,727 bln',
        country: 'USA' },
    { id: 'HSBC',
        currency: 'USD',
        bankName: 'HSBC Holdings plc',
        asset: '$2,558 bln',
        country: 'England' },
    { id: 'BoA',
        currency: 'USD',
        bankName: 'Bank of America',
        asset: '$2,354 bln',
        country: 'USA' },
    { id: 'BNP',
        currency: 'USD',
        bankName: 'BNP Pariba',
        asset: '$2,336 bln',
        country: 'France' },
    { id: 'CA',
        currency: 'USD',
        bankName: 'Crédit Agricole',
        asset: '$2,123 bln',
        country: 'France' }
]
